# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Card Name')),
                ('expansion', models.CharField(max_length=255, verbose_name=b'Card Expansion')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 28, 2, 6, 43, 857560))),
            ],
        ),
        migrations.CreateModel(
            name='WatchedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(verbose_name=b'API URL')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapi.Card')),
                ('vendor_quote', models.ManyToManyField(to='vendorapi.VendorQuote')),
            ],
        ),
    ]
