# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('multID', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('html', models.TextField(blank=True)),
                ('deckID', models.CharField(max_length=64)),
                ('md_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md', to='mtg.Card')),
                ('sb_cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sb', to='mtg.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=128)),
                ('eventTitle', models.CharField(blank=True, max_length=256)),
                ('date', models.DateField(null=True)),
                ('decks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mtg.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(default=b'Standard', max_length=10)),
                ('format_code', models.CharField(blank=True, default=b'ST', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FormatQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtg.EventFormat')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='format_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtg.FormatQuery'),
        ),
    ]
